import EmberRouter from '@ember/routing/router';
import config from 'dummy/config/environment';

export default class Router extends EmberRouter {
  location = config.locationType;
  rootURL = config.rootURL;
}

Router.map(function() {
  // this.route('docs', function() { // docs homepage (required)
  //   this.route('quickstart');
  //   this.route('usage');
  //   this.route('filtering');
  //   this.route('pagination');
  //   this.route('search');
  //   this.route('sorting');
  //
  //   this.route('api', function() { // autogenerated API homepage (required)
  //     this.route('item', {
  //       path: '/*path'
  //     }); // autogenerated API subpages (required)
  //   });
  // });
  this.route('not-found', {
    path: '/*path'
  });
});